# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-24 17:26
from __future__ import unicode_literals

from django.db import migrations
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('photologue', '0003_photo_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='gallery',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, to='photologue.Gallery'),
        ),
    ]
