# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-24 17:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photologue', '0006_auto_20180224_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='photos',
        ),
    ]
