# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-24 17:39
from __future__ import unicode_literals

from django.db import migrations
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('photologue', '0007_remove_gallery_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='photos',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, related_name='galleries', to='photologue.Photo', verbose_name='photos'),
        ),
    ]
