# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-24 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photologue', '0009_remove_photo_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='gallery',
            field=models.ManyToManyField(blank=True, to='photologue.Gallery'),
        ),
    ]
